export const CONFIRM_PASSWORD_MSG = 'Confirmation Password has to be equal.'
export const EMAIL_MSG = 'Invalid e-mail address.'
export const PASSWORD_MSG = 'Password has to be at least 8 characters long '
 + 'and contain at least one uppercase, lowercase and numeric character.'
export const REQUIRED_MSG = 'Required field.'
export const USED_EMAIL_MSG = 'You are already using this email.'
