export const SIGNUP_LOGIN_SUCCESS = 'SIGNUP_LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const EMAIL_CONFIRM_SUCCESS = 'EMAIL_CONFIRM_SUCCESS';
export const EMAIL_CONFIRM_FAILED = 'EMAIL_CONFIRM_FAILED';
export const EMAIL_RESEND_FETCHING = 'EMAIL_RESEND_FETCHING';
export const EMAIL_RESEND_SUCCESS = 'EMAIL_RESEND_SUCCESS';
export const EMAIL_RESEND_FAILED = 'EMAIL_RESEND_FAILED';

export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
